### ISSUE TITLE
Destroy SocketIOFile object after upload completed.

### ISSUE THREAD

**Issue by mmende** [rico345100/socket.io-file#11]
Hi,
Is it possible to destroy the SocketIOFile object or at least make it unavailable for the socket it was being created with after the upload completed e.g.?

Kind regards

**Comment by rico345100** [comment]
Sorry for late answer, I was kind of busy. That's quite good idea, I don't know why I forgot this to socket.io-file. I will add this asap. Thanks for suggestion!

**Comment by rico345100** [comment]
I just added destroy method for SocketIOFile :) Don't forget to upload to @2.0.2.
Note that calling destroy also destroy all client resources to invoke they're destroy method.

**Comment by rico345100** [comment]
Close this. You can re-open anytime you need.

**Comment by durek1337** [comment]
Hello! The destroy-method does not remove all the listeners on the socketio-socket. This is also not happening after abort und complete. I want to create the instance only when I need it and would like to have a clean cut before I initialize it again. This issue is more than this topic requests but I thought it's not worth a new one.

This is my current workaround with server.socket as Socket.io-Socket:
*Client*

```
const removeListeners = (id) => {
    server.socket
        .off('socket.io-file::disconnectByServer')
        .off('socket.io-file::recvSync')
        .off('socket.io-file::request::'+id)
}

```
*Client*
```
var removeListeners = (id) => {
      let li = [
        'socket.io-file::reqSync',
        'socket.io-file::createFile',
        'socket.io-file::stream::'+id,
        'socket.io-file::done::'+id,
        'socket.io-file::abort::'+id
      ]
      li.forEach((e,i) => {
        self.socket.removeAllListeners(e)
      })
    }
```
This makes the destroy method obsolete for me. I tried this workaround only on one-file-uploads.
