### ISSUE TITLE
Submit all form inputs

### ISSUE THREAD

**Issue by Wyzix33** [rico345100/socket.io-file#6]
Hi, can this module be used to submit all form elements. inputs and files at the same time? 
I need to send 1-2 files and some inputs values at the same time.
Or at least a single id with each file.
I was trying to emit a simple object by using readAsBinaryString and encode it to base64 and send all images along with form data ( {id: 1, file1: base64, file2: base64,otherinput: value ...} ), it works, but i am having problems with 50MB+ files so i'm after a module to do that for me.
Thanks and great job.

**Comment by rico345100** [comment]
@Wyzix33 Socket.io-file designed for just uploading file(s) into the server via Socket.io, not for uploading html form. If you just want to upload your form, you don't have to use this, just send do XHR with multipart encoded body as POST.

**Comment by Wyzix33** [comment]
So you can't send aditional information at the same time with the file?

**Comment by rico345100** [comment]
@Wyzix33 Basically, yes. And adding the feature of sending additional information is possible but I'm not gonna do that, because of the purpose of this module: "Sending file via Socket.io" as I said eariler.

If you want to send some data, not files, why don't you just send directly with Socket.io?

If you want to do that together, you'd better just to make your own with this module, whatever you needed. I want to keep this module to focusing on file upload, not universal data transmission or something like that.

It's glad to give me a good suggestion, but your request seems not suitable in this case. Thanks!

**Comment by rico345100** [comment]
I'm closing this. Any question or suggestion is welcome.
